apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kube-eventer
  name: kube-eventer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-eventer
  template:
    metadata:
      labels:
        app: kube-eventer
    spec:
      priorityClassName: system-cluster-critical
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: kube-eventer
      containers:
        - image: registry.aliyuncs.com/acs/kube-eventer:v1.2.7-ca03be0-aliyun
          name: kube-eventer
          command:
            - "/kube-eventer"
            - "--frequency=30s"
            - "--source=kubernetes:https://kubernetes.default"
            - "--sink=webhook:https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=510f69bb-c952-4fcf-9785-f4891d770ab4&level=Warning&kinds=IntegrationTest&header=Content-Type=application/json&custom_body_configmap=testplane-custom-body&custom_body_configmap_namespace=testplane-system&method=POST"
            - "--sink=webhook:https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=510f69bb-c952-4fcf-9785-f4891d770ab4&level=Normal&kinds=IntegrationTest&namespaces=default,testplane-system&header=Content-Type=application/json&custom_body_configmap=testplane-custom-body&custom_body_configmap_namespace=testplane-system&method=POST"
          env:
          - name: TZ
            value: "Asia/Shanghai"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: zoneinfo
              mountPath: /usr/share/zoneinfo
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 250Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-eventer
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-eventer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-eventer
subjects:
  - kind: ServiceAccount
    name: kube-eventer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-eventer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-body
data:
  content: |
    {
      "msgtype": "text",
      "text": {
        "content": "[TestPlane-eventer]\nEnv: qacloud\nType: {{ .Type }}\nKind: {{ .InvolvedObject.Kind }}\nNamespace: {{ .InvolvedObject.Namespace }}\nName: {{ .InvolvedObject.Name }}\nReason: {{ .Reason }}\nMessage: {{ .Message }}\nTime: {{ .LastTimestamp }}"
      }
    }
